[package]
name = "duelingbook-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
chromiumoxide = "0.8.0"
futures = "0.3.31"
serde_json = "1.0.146"
tokio = { version = "1.48.0", features = ["full"] }
